"""Headless UI regression with a mocked Tauri API; never opens the user database or sends mail."""
import os
import tempfile
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

from ui_fixtures import MOCK, UPDATE

artifacts = Path(tempfile.mkdtemp(prefix='novelsub-ui-'))
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    page=browser.new_page(viewport={"width":1440,"height":1000})
    errors=[]
    page.on('pageerror',lambda error: errors.append(str(error)))
    page.route('**/src/api.ts*',lambda route:route.fulfill(status=200,content_type='application/javascript',body=MOCK))
    page.route('**/*plugin-dialog*',lambda route:route.fulfill(status=200,content_type='application/javascript',body="export const save=async()=>'/tmp/novelsub-log-export-fixture.xlsx';"))
    page.route('**/src/update.ts*',lambda route:route.fulfill(status=200,content_type='application/javascript',body=UPDATE))
    page.clock.install()
    page.goto(os.environ.get('NOVELSUB_TEST_URL', 'http://127.0.0.1:5179'))
    page.wait_for_load_state('networkidle')
    success=page.locator('.stat').filter(has=page.get_by_text('今日成功',exact=True)).locator('.stat-value')
    expect(success).to_have_text('1封')
    before=page.evaluate("window.__calls.filter(c=>c.name==='dashboard').length")
    page.evaluate("for(let i=0;i<10;i++){window.__emit('log',{id:1,level:'success',category:'send'});window.__emit('reply',{id:305,kind:'human',accepted:false})}")
    page.wait_for_function("n=>window.__calls.filter(c=>c.name==='dashboard').length>n",arg=before)
    expect(success).to_have_text('1封')
    expect(page.locator('.dashboard-attention-list')).to_contain_text('累计 305 封人工回复')
    page.evaluate('window.__sentToday=0')
    page.clock.fast_forward(61_000)
    page.clock.fast_forward(250)
    expect(success).to_have_text('0封')
    page.get_by_role('button',name='投稿计划',exact=True).click()
    expect(page.locator('tbody')).to_contain_text('回归测试计划')
    expect(page.locator('.plan-progress-count')).to_have_text('1 / 3')
    expect(page.locator('.plans-table').get_by_role('button',name='编辑计划',exact=True)).to_be_disabled()
    page.locator('.plans-table').get_by_role('button',name='更多操作').click()
    expect(page.get_by_role('menuitem',name='停止发送')).to_be_visible()
    expect(page.get_by_role('menuitem',name='配置投稿邮箱')).to_be_disabled()
    page.keyboard.press('Escape')
    expect(page.get_by_role('menu')).to_have_count(0)
    assert not page.evaluate("window.__calls.filter(c=>c.name==='listDeliveries')")
    page.locator('tbody').get_by_role('button',name='暂停',exact=True).click()
    expect(page.locator('tbody').get_by_role('button',name='继续',exact=True)).to_be_visible()
    expect(page.locator('.plans-table').get_by_role('button',name='编辑计划',exact=True)).to_be_disabled()
    page.locator('.plans-table').get_by_role('button',name='更多操作').click()
    expect(page.get_by_role('menuitem',name='配置投稿邮箱')).to_be_disabled()
    page.keyboard.press('Escape')
    page.locator('tbody').get_by_role('button',name='继续',exact=True).click()
    expect(page.locator('tbody').get_by_role('button',name='暂停',exact=True)).to_be_visible()
    dashboard_calls=page.evaluate("window.__calls.filter(c=>c.name==='dashboard').length")
    engine_calls=page.evaluate("window.__calls.filter(c=>c.name==='runningTaskCount').length")
    page.evaluate("window.__emit('task',{...window.__task,sent:2})")
    page.clock.fast_forward(250)
    page.wait_for_function("n=>window.__calls.filter(c=>c.name==='runningTaskCount').length>n",arg=engine_calls)
    assert page.evaluate("window.__calls.filter(c=>c.name==='dashboard').length")==dashboard_calls
    expect(page.locator('.plan-progress-count')).to_have_text('2 / 3')
    assert not page.evaluate("window.__calls.filter(c=>c.name==='listDeliveries')")
    page.locator('tbody').get_by_role('button',name='记录',exact=True).click()
    expect(page.get_by_role('dialog')).to_be_visible()
    expect(page.get_by_role('dialog')).to_contain_text('a@example.com')
    expect(page.get_by_role('dialog').get_by_title('重新发送该编辑')).to_be_disabled()
    page.evaluate("window.__task.status='stopped';window.__emit('task',{...window.__task})")
    expect(page.get_by_role('dialog').get_by_title('重新发送该编辑')).to_be_enabled()
    page.get_by_role('dialog').locator('tbody tr').filter(has_text='b@example.com').get_by_role('button',name='手动发送',exact=True).click()
    expect(page.get_by_role('alertdialog')).to_be_visible()
    page.get_by_role('alertdialog').get_by_role('button',name='手动发送',exact=True).click()
    page.wait_for_function("typeof window.__finishManual==='function'")
    expect(page.get_by_role('dialog').get_by_title('重新发送该编辑')).to_be_disabled()
    expect(page.get_by_role('dialog').get_by_role('button',name='添加编辑',exact=True)).to_be_disabled()
    for button in page.get_by_role('dialog').get_by_title('移除该编辑',exact=True).all():
        expect(button).to_be_disabled()
    page.evaluate('window.__finishManual()')
    expect(page.get_by_role('dialog').get_by_role('button',name='添加编辑',exact=True)).to_be_enabled()
    page.wait_for_function("window.__calls.some(c=>c.name==='deliverySummaryPage'&&c.args[0]===1)")
    assert not page.evaluate("window.__calls.some(c=>c.name==='listDeliveries')")
    # Pending network results are visible and block another send until explicit reconciliation.
    page.evaluate("window.__pending=[{id:1,account_id:1,manuscript_id:1,task_id:1,recipient:'b@example.com',subject:'主题',message_id:'<pending>',created_at:'2026-09-06 10:00:00'}];window.__emit('log',{manuscript_id:1})")
    page.clock.fast_forward(250)
    expect(page.get_by_role('dialog')).to_contain_text('发送结果待确认')
    expect(page.get_by_role('dialog').get_by_role('button',name='添加编辑',exact=True)).to_be_disabled()
    page.screenshot(path=str(artifacts / 'pending-confirmation.png'),full_page=True)
    page.get_by_role('dialog').get_by_role('button',name='已发出，补记成功',exact=True).click()
    expect(page.get_by_role('alertdialog')).to_contain_text('不再发送邮件')
    page.get_by_role('alertdialog').get_by_role('button',name='已核对，补记成功',exact=True).click()
    expect(page.get_by_role('dialog').locator('[role="status"]')).to_have_count(0)
    expect(page.get_by_role('dialog').locator('tbody tr').filter(has_text='b@example.com')).to_contain_text('已发送')
    assert page.evaluate("window.__calls.filter(c=>c.name==='sendManualDelivery').length")==1
    # Late responses from an older filter never replace the current rows.
    page.evaluate('window.__deferDetail=true')
    page.get_by_role('dialog').get_by_placeholder('搜索姓名、平台、邮箱或备注').fill('a@example.com')
    page.wait_for_function("typeof window.__finishDetail==='function'")
    page.get_by_role('dialog').get_by_placeholder('搜索姓名、平台、邮箱或备注').fill('c@example.com')
    expect(page.get_by_role('dialog').locator('tbody')).to_contain_text('c@example.com')
    page.evaluate('window.__finishDetail()')
    expect(page.get_by_role('dialog').locator('tbody')).not_to_contain_text('a@example.com')
    page.evaluate('window.__failDetail=true')
    page.get_by_role('dialog').get_by_placeholder('搜索姓名、平台、邮箱或备注').fill('b@example.com')
    expect(page.get_by_role('dialog').get_by_role('alert')).to_contain_text('记录加载失败 fixture')
    expect(page.get_by_role('dialog').get_by_role('button',name='添加编辑',exact=True)).to_be_disabled()
    page.evaluate('window.__failDetail=false')
    page.get_by_role('dialog').get_by_role('button',name='重试加载',exact=True).click()
    expect(page.get_by_role('dialog').locator('tbody')).to_contain_text('b@example.com')
    page.get_by_role('dialog').get_by_placeholder('搜索姓名、平台、邮箱或备注').fill('')
    page.screenshot(path=str(artifacts / 'plan-detail.png'),full_page=True)
    page.keyboard.press('Escape')
    expect(page.get_by_role('dialog')).to_have_count(0)
    page.evaluate("window.__manuscript.recipients=[...window.__manuscript.recipients,...Array.from({length:20},(_,i)=>'extra'+i+'@example.com')]")
    page.locator('tbody').get_by_role('button',name='记录',exact=True).click()
    expect(page.get_by_role('dialog').locator('tbody tr')).to_have_count(10)
    expect(page.get_by_role('dialog').locator('.pager-meta')).to_contain_text('共 23 条')
    page.get_by_role('dialog').get_by_role('button',name='下一页',exact=True).click()
    expect(page.get_by_role('dialog').locator('.pager-meta')).to_contain_text('第 11–20 条')
    assert page.evaluate("window.__calls.filter(c=>c.name==='deliverySummaryPage').at(-1).args[5]")==10
    page.get_by_role('dialog').get_by_placeholder('搜索姓名、平台、邮箱或备注').fill('extra19@example.com')
    expect(page.get_by_role('dialog').locator('.pager-meta')).to_contain_text('第 1–1 条，共 1 条')
    expect(page.get_by_role('dialog').locator('tbody')).to_contain_text('extra19@example.com')
    page.get_by_role('dialog').get_by_placeholder('搜索姓名、平台、邮箱或备注').fill('')
    page.get_by_role('dialog').get_by_role('group',name='发送状态筛选').get_by_role('button',name='已发送',exact=True).click()
    expect(page.get_by_role('dialog').locator('.pager-meta')).to_contain_text('共 2 条')
    page.evaluate("window.__pending=[{id:2,account_id:1,manuscript_id:1,task_id:1,recipient:'c@example.com',subject:'主题',message_id:'<pending2>',created_at:'2026-09-06 10:00:00'}];window.__emit('log',{manuscript_id:1})")
    page.clock.fast_forward(250)
    expect(page.get_by_role('dialog')).to_contain_text('发送结果待确认')
    page.get_by_role('dialog').get_by_role('button',name='未发出，解除待确认',exact=True).click()
    expect(page.get_by_role('alertdialog')).to_contain_text('仅凭发件箱没有记录不足以确认')
    page.get_by_role('alertdialog').get_by_role('button',name='已核对，解除待确认',exact=True).click()
    expect(page.get_by_role('dialog').locator('[role="status"]')).to_have_count(0)
    assert page.evaluate("window.__calls.filter(c=>c.name==='sendManualDelivery').length")==1
    page.keyboard.press('Escape')
    expect(page.get_by_role('dialog')).to_have_count(0)
    page.get_by_role('button',name='收件箱',exact=True).click()
    expect(page.locator('.pager-meta')).to_contain_text('共 305 条')
    expect(page.locator('.reply-list-item')).to_have_count(20)
    page.get_by_role('button',name='16',exact=True).click()
    expect(page.locator('.reply-list-item')).to_have_count(5)
    expect(page.locator('.reply-list')).to_contain_text('最早的历史回复')
    page.get_by_placeholder('搜索邮件、编辑或邮箱').fill('最早')
    expect(page.locator('.pager-meta')).to_contain_text('共 1 条')
    expect(page.locator('.reply-list-item')).to_have_count(1)
    expect(page.locator('.pager-meta')).to_contain_text('第 1–1 条')
    page.screenshot(path=str(artifacts / 'replies.png'),full_page=True)
    page.get_by_role('button',name='发送记录',exact=True).click()
    expect(page.locator('.pager-meta')).to_contain_text('共 305 条')
    page.locator('.pager-size select').select_option('20')
    expect(page.locator('tbody tr')).to_have_count(20)
    page.get_by_role('button',name='16',exact=True).click()
    expect(page.locator('tbody tr')).to_have_count(5)
    expect(page.locator('tbody')).to_contain_text('最早的失败记录')
    page.get_by_placeholder('搜索发件 / 编辑邮箱').fill('old_100%')
    expect(page.locator('.pager-meta')).to_contain_text('共 1 条')
    expect(page.locator('.pager-meta')).to_contain_text('第 1–1 条')
    page.get_by_role('button',name='按结果筛选').click()
    page.get_by_role('option',name='失败',exact=True).click()
    expect(page.locator('tbody tr')).to_have_count(1)
    page.get_by_role('button',name='导出 Excel',exact=True).click()
    page.wait_for_function("window.__calls.some(c=>c.name==='exportLogs')")
    assert page.evaluate("window.__calls.find(c=>c.name==='exportLogs').args")==['/tmp/novelsub-log-export-fixture.xlsx',None,'error','old_100%']
    page.evaluate("window.__emit('log',{id:999,task_id:1,level:'success',recipient:'other@example.com'})")
    page.clock.fast_forward(250)
    expect(page.locator('tbody tr')).to_have_count(1)
    expect(page.locator('tbody')).to_contain_text('最早的失败记录')
    page.screenshot(path=str(artifacts / 'logs.png'),full_page=True)
    page.get_by_role('button',name='投稿统计',exact=True).click()
    expect(page.locator('.pager-meta')).to_contain_text('共 405 条')
    page.locator('.pager-size select').select_option('50')
    expect(page.locator('tbody tr')).to_have_count(50)
    page.get_by_role('button',name='9',exact=True).click()
    expect(page.locator('tbody tr')).to_have_count(5)
    page.locator('input[type=date]').nth(0).fill('2025-01-01')
    page.locator('input[type=date]').nth(1).fill('2025-01-03')
    expect(page.locator('.pager-meta')).to_contain_text('共 3 条')
    expect(page.locator('.pager-meta')).to_contain_text('第 1–3 条')
    expect(page.locator('.stats-card-value').first).to_have_text('3')
    page.locator('input[type=date]').nth(0).fill('2025-02-01')
    expect(page.locator('.notice-error')).to_contain_text('开始日期')
    expect(page.locator('.stats-cards')).to_have_count(0)
    page.get_by_role('button',name='全部',exact=True).click()
    expect(page.locator('input[type=date]').nth(0)).to_have_value('')
    expect(page.locator('input[type=date]').nth(1)).to_have_value('')
    expect(page.locator('.pager-meta')).to_contain_text('共 405 条')
    page.get_by_role('button',name='统计粒度',exact=True).click()
    page.get_by_role('option',name='按月统计',exact=True).click()
    expect(page.locator('.pager-meta')).to_contain_text('共 14 条')
    expect(page.locator('tbody tr')).to_have_count(6)
    page.get_by_role('button',name='下一页',exact=True).click()
    expect(page.locator('tbody tr')).to_have_count(6)
    page.get_by_role('button',name='下一页',exact=True).click()
    expect(page.locator('tbody tr')).to_have_count(2)
    page.get_by_role('button',name='上一页',exact=True).click()
    page.screenshot(path=str(artifacts / 'stats.png'),full_page=True)
    assert not errors, errors
    print('PASS: 23 recipient detail backend pagination/search/status filter, stale-response suppression, load failure retry, both pending-result confirmations without SMTP; active task blocks historical resend; pending manual send locks mutations; 405 stats periods bounded to 50 rows, filter/page reset and errors cleared, pause/resume controls; dashboard persisted counters do not double-count, minute refresh and lightweight engine query; 305 logs with server filters and matching export;  active config locked; task events update current-round progress without delivery refetch; scoped detail history; 305 replies paginated and oldest reply searchable; no browser exceptions')
    print(f"Screenshots: {artifacts}")
    browser.close()
