//! Classify an inbound mail as auto-reply, bounce, or human reply.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReplyKind {
    Auto,
    Human,
    Bounce,
}

impl ReplyKind {
    pub fn as_str(self) -> &'static str {
        match self {
            ReplyKind::Auto => "auto",
            ReplyKind::Human => "human",
            ReplyKind::Bounce => "bounce",
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct IncomingMail {
    pub from: String,
    pub subject: String,
    pub body: String,
    pub auto_submitted: String,
    pub precedence: String,
    pub content_type: String,
    pub extra_headers: Vec<(String, String)>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Classification {
    pub kind: ReplyKind,
    pub reason: String,
}

pub fn classify(mail: &IncomingMail) -> Classification {
    let from = mail.from.to_lowercase();
    let subject = mail.subject.to_lowercase();
    let body = unique_body(&mail.body);
    let body_l = body.to_lowercase();
    let auto_submitted = mail.auto_submitted.to_lowercase();
    let precedence = mail.precedence.to_lowercase();
    let content_type = mail.content_type.to_lowercase();
    let headers = mail
        .extra_headers
        .iter()
        .map(|(k, v)| (k.to_lowercase(), v.to_lowercase()))
        .collect::<Vec<_>>();

    if is_bounce(&from, &subject, &body_l, &content_type, &headers) {
        return Classification {
            kind: ReplyKind::Bounce,
            reason: "退信或投递失败通知".into(),
        };
    }

    let mut auto = 0i32;
    let mut reasons: Vec<&str> = Vec::new();

    if auto_submitted.contains("auto-replied") || auto_submitted.contains("auto-generated") {
        auto += 6;
        reasons.push("邮件头 Auto-Submitted");
    }
    if precedence.contains("auto") || precedence.contains("bulk") || precedence.contains("junk") {
        auto += 3;
        reasons.push("邮件头 Precedence");
    }
    if header_present(&headers, "x-autoreply")
        || header_present(&headers, "x-auto-reply")
        || header_present(&headers, "x-autogenerated")
        || header_present(&headers, "x-autoreply")
    {
        auto += 5;
        reasons.push("自动回复专用头");
    }
    if is_noreply_from(&from) {
        auto += 4;
        reasons.push("发件人是系统地址");
    }
    if subject_is_auto(&subject) {
        auto += 4;
        reasons.push("主题像自动回复");
    }
    if body_is_auto(&body_l) {
        auto += 3;
        reasons.push("正文像自动回复");
    }

    let mut human = 0i32;
    if body.chars().count() >= 80 {
        human += 2;
    }
    if body_is_editorial(&body_l) {
        human += 4;
    }
    if auto_submitted.trim() == "no" {
        human += 2;
    }

    if auto >= 3 && auto >= human {
        let reason = if reasons.is_empty() {
            "综合判定为自动回复".into()
        } else {
            format!("判定为自动回复：{}", reasons.join("、"))
        };
        return Classification {
            kind: ReplyKind::Auto,
            reason,
        };
    }

    Classification {
        kind: ReplyKind::Human,
        reason: if body_is_editorial(&body_l) {
            "正文像编辑人工回复".into()
        } else if auto == 0 {
            "没有自动回复特征，按人工回复处理".into()
        } else {
            "自动回复特征不足，按人工回复处理".into()
        },
    }
}

fn header_present(headers: &[(String, String)], name: &str) -> bool {
    headers.iter().any(|(k, v)| k == name && v != "no" && !v.is_empty())
}

fn is_noreply_from(from: &str) -> bool {
    const MARKERS: &[&str] = &[
        "mailer-daemon",
        "postmaster",
        "no-reply",
        "noreply",
        "donotreply",
        "do-not-reply",
        "autoreply",
        "auto-reply",
        "autoresponder",
        "bounce",
        "mailerdaemon",
    ];
    MARKERS.iter().any(|m| from.contains(m))
}

fn is_bounce(
    from: &str,
    subject: &str,
    body: &str,
    content_type: &str,
    headers: &[(String, String)],
) -> bool {
    if content_type.contains("multipart/report") || content_type.contains("delivery-status") {
        return true;
    }
    if header_present(headers, "x-failed-recipients") {
        return true;
    }
    if from.contains("mailer-daemon") || from.contains("postmaster") {
        return true;
    }
    const SUBJ: &[&str] = &[
        "undeliverable",
        "undelivered",
        "delivery status",
        "delivery failure",
        "returned mail",
        "mail delivery failed",
        "failure notice",
        "无法投递",
        "投递失败",
        "退信",
        "退回",
        "地址不存在",
    ];
    SUBJ.iter().any(|k| subject.contains(k)) || body.contains("diagnostic-code")
}

fn subject_is_auto(subject: &str) -> bool {
    const KEYS: &[&str] = &[
        "自动回复",
        "自動回覆",
        "自动回信",
        "系统邮件",
        "请勿回复",
        "請勿回覆",
        "out of office",
        "out-of-office",
        "autoreply",
        "auto-reply",
        "auto reply",
        "automatic reply",
        "vacation",
        "不在办公室",
        "不在辦公室",
        "请假通知",
        "休假",
    ];
    KEYS.iter().any(|k| subject.contains(k))
}

fn body_is_auto(body: &str) -> bool {
    const KEYS: &[&str] = &[
        "这是一封自动回复",
        "此邮件为自动回复",
        "本邮件为系统自动",
        "系统自动发送",
        "系统自动发出",
        "此邮件由系统发出",
        "请勿回复此邮件",
        "请不要回复此邮件",
        "请勿直接回复",
        "do not reply",
        "this is an automatic",
        "automatically generated",
        "out of office",
        "不在办公室",
        "我会尽快回复",
        "将尽快回复",
        "已收到您的邮件",
        "已收到您的来稿",
        "已收到您的投稿",
        "感谢您的投稿",
        "感谢您投稿",
        "稿件已收到",
        "稿件已经收到",
        "稿件已进入",
        "来稿已收",
    ];
    KEYS.iter().any(|k| body.contains(k))
}

fn body_is_editorial(body: &str) -> bool {
    const KEYS: &[&str] = &[
        "审稿",
        "審稿",
        "采用",
        "採用",
        "退稿",
        "修改意见",
        "修改建議",
        "责编",
        "責編",
        "编辑部",
        "編輯部",
        "签约",
        "簽約",
        "请按意见修改",
        "建议修改",
        "不符合我们",
        "通过审核",
        "进入终审",
        "进入二审",
    ];
    KEYS.iter().any(|k| body.contains(k))
}

fn unique_body(body: &str) -> String {
    let mut lines = Vec::new();
    for line in body.lines() {
        let t = line.trim();
        if t.starts_with('>') {
            continue;
        }
        if t.starts_with("On ") && t.contains("wrote") {
            break;
        }
        if t.contains("原始邮件") || t.contains("Original Message") || t.contains("转发的邮件") {
            break;
        }
        if t.starts_with("-----") {
            break;
        }
        if t.starts_with("在 ") && (t.contains("写道") || t.contains("寫道")) {
            break;
        }
        lines.push(t);
    }
    lines.join("\n").trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mail(from: &str, subject: &str, body: &str) -> IncomingMail {
        IncomingMail {
            from: from.into(),
            subject: subject.into(),
            body: body.into(),
            ..IncomingMail::default()
        }
    }

    #[test]
    fn auto_submitted_header() {
        let mut m = mail("editor@site.com", "Re: 投石穿云", "已收到");
        m.auto_submitted = "auto-replied".into();
        assert_eq!(classify(&m).kind, ReplyKind::Auto);
    }

    #[test]
    fn chinese_auto_subject() {
        let m = mail("noreply@site.com", "自动回复：已收到投稿", "请勿回复此邮件，这是系统自动发送的。");
        assert_eq!(classify(&m).kind, ReplyKind::Auto);
    }

    #[test]
    fn editorial_human() {
        let m = mail(
            "zhangsan@qidian.com",
            "Re: 投石穿云",
            "您好，责编看过第一章，建议修改开篇节奏，进入二审前请先按意见改一版。",
        );
        assert_eq!(classify(&m).kind, ReplyKind::Human);
    }

    #[test]
    fn bounce_mailer_daemon() {
        let m = mail("MAILER-DAEMON@qq.com", "Undelivered Mail Returned to Sender", "Diagnostic-Code: smtp; 550");
        assert_eq!(classify(&m).kind, ReplyKind::Bounce);
    }

    #[test]
    fn received_manuscript_auto() {
        let m = mail(
            "tougao@web.com",
            "投稿确认",
            "感谢您的投稿，稿件已进入审核队列。此邮件由系统发出，请勿回复。",
        );
        assert_eq!(classify(&m).kind, ReplyKind::Auto);
    }

    #[test]
    fn short_plain_reply_is_human() {
        let m = mail("editor@site.com", "Re: 投石穿云", "方便今晚十点通话吗？我是责编李四。");
        assert_eq!(classify(&m).kind, ReplyKind::Human);
    }
}
